[package]
name = "nesql-node"
description = "napi-rs bindings for the nesql CLI crate -> the nesql-engine npm package."
version = "8.0.0"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/Eth-Interchained/neSQL"

[lib]
crate-type = ["cdylib"]

[dependencies]
nedb-engine = "8.0.0"
nesql = "8.0.0"
serde_json = { version = "1", features = ["preserve_order"] }
napi = { version = "2", default-features = false, features = ["napi8"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
